#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]

use crate::*;

/////////////////////////////
// sounds.h
/////////////////////////////
//
// DESCRIPTION:
//	Created by the sound utility written by Dave Taylor.
//	Kept as a sample, DOOM2  sounds. Frozen.
//

//
// Identifiers for all music in game.
//

pub enum musicenum_t {
    mus_None,
    mus_e1m1,
    mus_e1m2,
    mus_e1m3,
    mus_e1m4,
    mus_e1m5,
    mus_e1m6,
    mus_e1m7,
    mus_e1m8,
    mus_e1m9,
    mus_e2m1,
    mus_e2m2,
    mus_e2m3,
    mus_e2m4,
    mus_e2m5,
    mus_e2m6,
    mus_e2m7,
    mus_e2m8,
    mus_e2m9,
    mus_e3m1,
    mus_e3m2,
    mus_e3m3,
    mus_e3m4,
    mus_e3m5,
    mus_e3m6,
    mus_e3m7,
    mus_e3m8,
    mus_e3m9,
    mus_inter,
    mus_intro,
    mus_bunny,
    mus_victor,
    mus_introa,
    mus_runnin,
    mus_stalks,
    mus_countd,
    mus_betwee,
    mus_doom,
    mus_the_da,
    mus_shawn,
    mus_ddtblu,
    mus_in_cit,
    mus_dead,
    mus_stlks2,
    mus_theda2,
    mus_doom2,
    mus_ddtbl2,
    mus_runni2,
    mus_dead2,
    mus_stlks3,
    mus_romero,
    mus_shawn2,
    mus_messag,
    mus_count2,
    mus_ddtbl3,
    mus_ampie,
    mus_theda3,
    mus_adrian,
    mus_messg2,
    mus_romer2,
    mus_tense,
    mus_shawn3,
    mus_openin,
    mus_evil,
    mus_ultima,
    mus_read_m,
    mus_dm2ttl,
    mus_dm2int,
    NUMMUSIC,
}

//
// Identifiers for all sfx in game.
//

pub enum sfxenum_t {
    sfx_None,
    sfx_pistol,
    sfx_shotgn,
    sfx_sgcock,
    sfx_dshtgn,
    sfx_dbopn,
    sfx_dbcls,
    sfx_dbload,
    sfx_plasma,
    sfx_bfg,
    sfx_sawup,
    sfx_sawidl,
    sfx_sawful,
    sfx_sawhit,
    sfx_rlaunc,
    sfx_rxplod,
    sfx_firsht,
    sfx_firxpl,
    sfx_pstart,
    sfx_pstop,
    sfx_doropn,
    sfx_dorcls,
    sfx_stnmov,
    sfx_swtchn,
    sfx_swtchx,
    sfx_plpain,
    sfx_dmpain,
    sfx_popain,
    sfx_vipain,
    sfx_mnpain,
    sfx_pepain,
    sfx_slop,
    sfx_itemup,
    sfx_wpnup,
    sfx_oof,
    sfx_telept,
    sfx_posit1,
    sfx_posit2,
    sfx_posit3,
    sfx_bgsit1,
    sfx_bgsit2,
    sfx_sgtsit,
    sfx_cacsit,
    sfx_brssit,
    sfx_cybsit,
    sfx_spisit,
    sfx_bspsit,
    sfx_kntsit,
    sfx_vilsit,
    sfx_mansit,
    sfx_pesit,
    sfx_sklatk,
    sfx_sgtatk,
    sfx_skepch,
    sfx_vilatk,
    sfx_claw,
    sfx_skeswg,
    sfx_pldeth,
    sfx_pdiehi,
    sfx_podth1,
    sfx_podth2,
    sfx_podth3,
    sfx_bgdth1,
    sfx_bgdth2,
    sfx_sgtdth,
    sfx_cacdth,
    sfx_skldth,
    sfx_brsdth,
    sfx_cybdth,
    sfx_spidth,
    sfx_bspdth,
    sfx_vildth,
    sfx_kntdth,
    sfx_pedth,
    sfx_skedth,
    sfx_posact,
    sfx_bgact,
    sfx_dmact,
    sfx_bspact,
    sfx_bspwlk,
    sfx_vilact,
    sfx_noway,
    sfx_barexp,
    sfx_punch,
    sfx_hoof,
    sfx_metal,
    sfx_chgun,
    sfx_tink,
    sfx_bdopn,
    sfx_bdcls,
    sfx_itmbk,
    sfx_flame,
    sfx_flamst,
    sfx_getpow,
    sfx_bospit,
    sfx_boscub,
    sfx_bossit,
    sfx_bospn,
    sfx_bosdth,
    sfx_manatk,
    sfx_mandth,
    sfx_sssit,
    sfx_ssdth,
    sfx_keenpn,
    sfx_keendt,
    sfx_skeact,
    sfx_skesit,
    sfx_skeatk,
    sfx_radio,
    NUMSFX,
}

/////////////////////////////
// sounds.c
/////////////////////////////
//
// DESCRIPTION:
//	Created by a sound utility.
//	Kept as a sample, DOOM2 sounds.
//

//
// Information about all the music
//

/////////////////////////////
// Sounds
/////////////////////////////

pub struct sounds<'a> {
    pub S_music: [musicinfo_t<'a>; 68],
    pub S_sfx: [sfxinfo_t<'a>; 109],
}

impl<'a> sounds<'a> {
    pub fn new() -> Self {
        //
        // Information about all the music
        //
        let S_music: [musicinfo_t; 68] = [
            musicinfo_t {
                name: "",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e1m1",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e1m2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e1m3",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e1m4",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e1m5",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e1m6",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e1m7",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e1m8",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e1m9",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e2m1",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e2m2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e2m3",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e2m4",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e2m5",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e2m6",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e2m7",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e2m8",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e2m9",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e3m1",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e3m2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e3m3",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e3m4",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e3m5",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e3m6",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e3m7",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e3m8",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "e3m9",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "inter",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "intro",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "bunny",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "victor",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "introa",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "runnin",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "stalks",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "countd",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "betwee",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "doom",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "the_da",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "shawn",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "ddtblu",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "in_cit",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "dead",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "stlks2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "theda2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "doom2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "ddtbl2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "runni2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "dead2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "stlks3",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "romero",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "shawn2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "messag",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "count2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "ddtbl3",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "ampie",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "theda3",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "adrian",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "messg2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "romer2",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "tense",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "shawn3",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "openin",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "evil",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "ultima",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "read_m",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "dm2ttl",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
            musicinfo_t {
                name: "dm2int",
                lumpnum: 0,
                data: ptr::null_mut(),
                handle: ptr::null_mut(),
            },
        ];
        //
        // Information about all the sfx
        //
        let S_sfx: [sfxinfo_t; 109] = [
            // S_sfx[0] needs to be a dummy for odd reasons.
            sfxinfo_t {
                tagname: "",
                name: "none",
                priority: 0,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "pistol",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "shotgn",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sgcock",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "dshtgn",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "dbopn",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "dbcls",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "dbload",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "plasma",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bfg",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sawup",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sawidl",
                priority: 118,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sawful",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sawhit",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "rlaunc",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "rxplod",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "firsht",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "firxpl",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "pstart",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "pstop",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "doropn",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "dorcls",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "stnmov",
                priority: 119,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "swtchn",
                priority: 78,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "swtchx",
                priority: 78,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "plpain",
                priority: 96,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "dmpain",
                priority: 96,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "popain",
                priority: 96,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "vipain",
                priority: 96,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "mnpain",
                priority: 96,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "pepain",
                priority: 96,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "slop",
                priority: 78,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "itemup",
                priority: 78,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "wpnup",
                priority: 78,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "oof",
                priority: 96,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "telept",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "posit1",
                priority: 98,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "posit2",
                priority: 98,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "posit3",
                priority: 98,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bgsit1",
                priority: 98,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bgsit2",
                priority: 98,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sgtsit",
                priority: 98,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "cacsit",
                priority: 98,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "brssit",
                priority: 94,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "cybsit",
                priority: 92,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "spisit",
                priority: 90,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bspsit",
                priority: 90,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "kntsit",
                priority: 90,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "vilsit",
                priority: 90,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "mansit",
                priority: 90,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "pesit",
                priority: 90,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sklatk",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sgtatk",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "skepch",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "vilatk",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "claw",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "skeswg",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "pldeth",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "pdiehi",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "podth1",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "podth2",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "podth3",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bgdth1",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bgdth2",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sgtdth",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "cacdth",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "skldth",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "brsdth",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "cybdth",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "spidth",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bspdth",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "vildth",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "kntdth",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "pedth",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "skedth",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "posact",
                priority: 120,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bgact",
                priority: 120,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "dmact",
                priority: 120,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bspact",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bspwlk",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "vilact",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "noway",
                priority: 78,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "barexp",
                priority: 60,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "punch",
                priority: 64,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "hoof",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "metal",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "chgun",
                priority: 64,
                //BUG
                //link: &S_sfx[sfxenum_t::sfx_pistol as usize],
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "tink",
                priority: 60,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bdopn",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bdcls",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "itmbk",
                priority: 100,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "flame",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "flamst",
                priority: 32,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "getpow",
                priority: 60,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bospit",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "boscub",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bossit",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bospn",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "bosdth",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "manatk",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "mandth",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "sssit",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "ssdth",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "keenpn",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "keendt",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "skeact",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "skesit",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "skeatk",
                priority: 70,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
            sfxinfo_t {
                tagname: "",
                name: "radio",
                priority: 60,
                link: ptr::null_mut(),
                pitch: -1,
                volume: -1,
                usefulness: 0,
                lumpnum: 0,
                numchannels: -1,
                driver_data: ptr::null_mut(),
            },
        ];

        Self { S_music, S_sfx }
    }
}

pub fn MUSIC(name: &str) -> musicinfo_t {
    return musicinfo_t {
        name: "",
        lumpnum: 0,
        data: ptr::null_mut(),
        handle: ptr::null_mut(),
    };
}

pub fn SOUND(name: &str, priority: i32) -> sfxinfo_t {
    return sfxinfo_t {
        tagname: "",
        name,
        priority,
        link: ptr::null_mut(),
        pitch: -1,
        volume: -1,
        usefulness: 0,
        lumpnum: 0,
        numchannels: -1,
        driver_data: ptr::null_mut(),
    };
}

pub fn SOUND_LINK<'a>(
    name: &'a str,
    priority: i32,
    link_id: usize,
    pitch: i32,
    volume: i32,
) -> sfxinfo_t<'a> {
    return sfxinfo_t {
        tagname: "",
        name,
        priority,
        //link: &mut S_sfx[link_id],
        link: ptr::null_mut(),
        pitch,
        volume,
        usefulness: 0,
        lumpnum: 0,
        numchannels: -1,
        driver_data: ptr::null_mut(),
    };
}
